import { StyleSheet } from 'react-native'

const readStyles = (colors: ColorScheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.white,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerButton: {
      padding: 8,
      width: 40,
      alignItems: 'center',
    },
    headerIcon: {
      fontSize: 20,
      color: colors.textDark,
    },
    headerCenter: {
      alignItems: 'center',
    },
    chapterNumber: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textDark,
      letterSpacing: 0.5,
    },
    timeRemaining: {
      fontSize: 11,
      color: colors.textSecondary,
      marginTop: 2,
    },
    contentContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    contentInner: {
      paddingHorizontal: 24,
      paddingTop: 16,
      paddingBottom: 140,
    },
    chapterTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.textDark,
      marginBottom: 28,
      lineHeight: 30,
      textAlign: 'center',
      letterSpacing: 1.5,
      textTransform: 'uppercase',
    },
    paragraph: {
      fontSize: 17,
      lineHeight: 30,
      color: colors.textDark,
      marginBottom: 24,
      textAlign: 'justify',
      letterSpacing: 0.2,
    },
    dropCap: {
      fontSize: 38,
      fontWeight: '800',
      color: colors.primary,
      lineHeight: 38,
      marginRight: 6,
    },
    toolsFab: {
      position: 'absolute',
      right: 16,
      bottom: 90,
      backgroundColor: colors.primary,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 999,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
      elevation: 6,
    },
    toolsFabText: {
      color: colors.white,
      fontWeight: '700',
      fontSize: 12,
    },
    navigationContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.black,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    navArrow: {
      width: 44,
      height: 44,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
    },
    navArrowText: {
      fontSize: 24,
      color: colors.white,
      fontWeight: '300',
    },
    aiAssistantButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primary,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 25,
    },
    aiAssistantIcon: {
      fontSize: 16,
      marginRight: 8,
    },
    aiAssistantText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.white,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.white,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '84%',
      padding: 20,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingBottom: 10,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: 0.5,
    },
    closeButton: {
      padding: 5,
    },
    closeButtonText: {
      fontSize: 20,
      color: colors.textSecondary,
    },
    modalBody: {
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      marginTop: 15,
      marginBottom: 6,
      color: colors.textDark,
    },
    modalText: {
      fontSize: 14,
      lineHeight: 22,
      color: colors.textPrimary,
    },
    bulletItem: {
      fontSize: 14,
      marginLeft: 10,
      lineHeight: 22,
      color: colors.textPrimary,
    },
    characterCard: {
      padding: 12,
      backgroundColor: colors.cardBackground,
      borderRadius: 10,
      marginBottom: 10,
    },
    characterName: {
      fontWeight: '700',
      fontSize: 14,
      color: colors.textDark,
      marginBottom: 4,
    },
    textInput: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      padding: 10,
      minHeight: 80,
      textAlignVertical: 'top',
      marginBottom: 10,
      color: colors.textPrimary,
    },
    primaryButton: {
      backgroundColor: colors.primary,
      padding: 12,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 10,
    },
    primaryButtonText: {
      color: colors.white,
      fontWeight: '700',
    },
    secondaryButton: {
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 12,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 10,
    },
    secondaryButtonText: {
      color: colors.textDark,
      fontWeight: '700',
    },
    noteItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      gap: 12,
    },
    deleteText: {
      color: '#BA3A3A',
      fontSize: 12,
      fontWeight: '700',
    },
    tocItem: {
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    tocLockedItem: {
      opacity: 0.5,
    },
    tocItemText: {
      fontSize: 16,
      color: colors.textDark,
    },
    toolsList: {
      gap: 10,
    },
    toolRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 10,
      borderRadius: 10,
      backgroundColor: colors.cardBackground,
    },
    toolIcon: {
      fontSize: 18,
    },
    toolText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textDark,
    },
    summaryCard: {
      flexDirection: 'row',
      gap: 12,
      backgroundColor: colors.cardBackground,
      borderRadius: 12,
      padding: 10,
      marginBottom: 8,
    },
    summaryTextWrap: {
      flex: 1,
    },
  })

export default readStyles
