import { StyleSheet } from 'react-native';

const readStyles = (colors: ColorScheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerButton: {
    padding: 8,
    width: 40,
    alignItems: 'center',
  },
  headerIcon: {
    fontSize: 20,
    color: colors.textDark,
  },
  headerCenter: {
    alignItems: 'center',
  },
  chapterNumber: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textDark,
    letterSpacing: 0.5,
  },
  timeRemaining: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  contentContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentInner: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 140,
  },
  chapterTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 28,
    lineHeight: 30,
    textAlign: 'center',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  paragraph: {
    fontSize: 17,
    lineHeight: 30,
    color: colors.textDark,
    marginBottom: 24,
    textAlign: 'justify',
    letterSpacing: 0.2,
  },
  dropCap: {
    fontSize: 38,
    fontWeight: '800',
    color: colors.primary,
    lineHeight: 38,
    marginRight: 6,
  },
  navigationContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.black,
    paddingHorizontal: 10,
    paddingVertical: 12,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    gap: 6,
  },
  navArrow: {
    width: 40,
    height: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navArrowText: {
    fontSize: 24,
    color: colors.white,
    fontWeight: '300',
  },
  readingToolsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#3A3A3A',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 20,
  },
  aiAssistantButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 20,
  },
  aiAssistantIcon: {
    fontSize: 14,
    marginRight: 6,
    color: colors.white,
  },
  aiAssistantText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.white,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'flex-end',
  },
  toolsModalContent: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    gap: 10,
  },
  toolsItem: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: colors.cardBackground,
  },
  toolsSelected: {
    backgroundColor: colors.primary,
  },
  toolsItemText: {
    color: colors.textDark,
    fontWeight: '600',
  },
  toolsItemTextSelected: {
    color: colors.white,
    fontWeight: '700',
  },
  modalContent: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '86%',
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 12,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textDark,
  },
  closeButton: { padding: 5 },
  closeButtonText: {
    fontSize: 20,
    color: colors.textSecondary,
  },
  modalBody: { marginBottom: 20 },
  heroCard: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 14,
    alignItems: 'center',
  },
  heroTextWrap: { flex: 1 },
  heroTitle: {
    fontSize: 24,
    color: colors.textDark,
    fontWeight: '700',
  },
  heroSubtitle: {
    marginTop: 6,
    color: colors.textSecondary,
    letterSpacing: 0.8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    marginTop: 14,
    marginBottom: 8,
    color: colors.textDark,
  },
  modalText: {
    fontSize: 14,
    lineHeight: 24,
    color: colors.textPrimary,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    backgroundColor: colors.cardBackground,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    color: colors.textDark,
  },
  statsCard: {
    marginTop: 16,
    backgroundColor: colors.primary,
    borderRadius: 16,
    padding: 16,
  },
  statsBig: {
    color: colors.white,
    fontSize: 30,
    fontWeight: '800',
  },
  statsLabel: {
    color: '#D2E8E2',
    marginBottom: 6,
  },
  characterCard: {
    padding: 12,
    backgroundColor: colors.cardBackground,
    borderRadius: 10,
    marginBottom: 8,
  },
  characterName: {
    fontWeight: '700',
    fontSize: 14,
    color: colors.textDark,
    marginBottom: 4,
  },
  textInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 10,
    minHeight: 90,
    textAlignVertical: 'top',
    marginBottom: 10,
    color: colors.textPrimary,
    backgroundColor: colors.white,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  noteItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: 8,
  },
  noteTextWrap: { flex: 1 },
  captionText: {
    fontSize: 12,
    marginTop: 4,
    color: colors.textSecondary,
  },
  deleteText: {
    color: '#C94343',
    fontSize: 12,
    fontWeight: '700',
  },
  tocItem: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tocItemText: {
    fontSize: 16,
    color: colors.textDark,
  },
});

export default readStyles;
