// ─── Local book data (bundled / offline) ────────────────────────────────────
export const GUEST_BOOKS: Book[] = [
  {
    _id: 'guest-1',
    bookId: 'guest-1',
    coverImage:
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=500&q=60',
    progressPercentage: 75,
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=500&q=60',
    genre: 'Science Fiction',
    genres: ['Science Fiction'],
    price: '0',
    description:
      'A lone astronaut must save the earth from disaster in this propulsive science-fiction thriller from the bestselling author of The Martian.',
    user: {
      _id: 'g1',
      username: 'Sci-Fi Shelf',
      profileImage: 'https://i.pravatar.cc/100?img=14',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'guest-2',
    bookId: 'guest-2',
    coverImage:
      'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=500&q=60',
    progressPercentage: 30,
    title: 'The Midnight Library',
    author: 'Matt Haig',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=500&q=60',
    genre: 'Fiction',
    genres: ['Fiction'],
    price: '0',
    description:
      'Between life and death there is a library, and within that library, the shelves go on forever. While there she must ask herself: what is it that makes a life worth living?',
    user: {
      _id: 'g2',
      username: 'Fiction Club',
      profileImage: 'https://i.pravatar.cc/100?img=9',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'guest-3',
    bookId: 'guest-3',
    coverImage:
      'https://images.unsplash.com/photo-1474932430478-367dbb6832c1?auto=format&fit=crop&w=500&q=60',
    progressPercentage: 0,
    title: 'Foundation',
    author: 'Isaac Asimov',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=500&q=60',
    genre: 'Science Fiction',
    genres: ['Science Fiction'],
    price: '0',
    description:
      'A masterpiece of galactic empires and psychohistory that matches the scope of the fall of Rome.',
    user: {
      _id: 'g3',
      username: 'Classic SF',
      profileImage: 'https://i.pravatar.cc/100?img=3',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'guest-4',
    bookId: 'guest-4',
    coverImage:
      'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=500&q=60',
    progressPercentage: 0,
    title: 'Dark Matter',
    author: 'Blake Crouch',
    image: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?auto=format&fit=crop&w=500&q=60',
    genre: 'Thriller',
    genres: ['Thriller'],
    price: '0',
    description:
      "Blake Crouch's reality-bending thriller is perfect for fans of your favorite mind-bending sci-fi stories.",
    user: {
      _id: 'g4',
      username: 'Thriller Hub',
      profileImage: 'https://i.pravatar.cc/100?img=7',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'guest-5',
    bookId: 'guest-5',
    coverImage:
      'https://images.unsplash.com/photo-1491841550275-ad7854e35ca6?auto=format&fit=crop&w=500&q=60',
    progressPercentage: 0,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=500&q=60',
    genre: 'Classic',
    genres: ['Classic'],
    price: '0',
    description: 'A portrait of the Jazz Age in all its decadence and excess.',
    user: {
      _id: 'g5',
      username: 'Classics Corner',
      profileImage: 'https://i.pravatar.cc/100?img=11',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'guest-6',
    bookId: 'guest-6',
    coverImage:
      'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=500&q=60',
    progressPercentage: 0,
    title: 'Circe',
    author: 'Madeline Miller',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=60',
    genre: 'Fantasy',
    genres: ['Fantasy'],
    price: '0',
    description: 'A bold retelling of the goddess of transformation from Greek mythology.',
    user: {
      _id: 'g6',
      username: 'Myth Readers',
      profileImage: 'https://i.pravatar.cc/100?img=5',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'guest-7',
    bookId: 'guest-7',
    coverImage:
      'https://images.unsplash.com/photo-1513002749550-c59d786b8e6c?auto=format&fit=crop&w=500&q=60',
    progressPercentage: 0,
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=500&q=60',
    genre: 'Science Fiction',
    genres: ['Science Fiction'],
    price: '0',
    description: 'A magnificent novel of hope, courage, and the enduring human spirit.',
    user: {
      _id: 'g7',
      username: 'Literary Picks',
      profileImage: 'https://i.pravatar.cc/100?img=2',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]